addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 0f239e0c-46ae-4aa8-b488-5f8ce8f12b08
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
script: mvn test-compile
sudo: 'false'
# Modified by Insights Service at 2016-07-14 05:33:33.232957
